user: 用户输入 {
  shape: person
}
user -> get_dir
get_dir {
  cli
  gui
  tui
}

get_dir -> "Dir::new": dir_path

"Dir::new" {
  read_dir -> Dir.files
  get_dir_name -> Dir.dir_name
  Dir {
    shape: stored_data
    files
    dir_name
    dir_path
  }
}

"Dir::new".Dir -> "InputDir::new": sort_files_by_name_unstable

"InputDir::new" {
  shape: stored_data
  BaseDir {
    shape: stored_data
    files
    dir_path
    dir_name
  }
  ModifyDir {
    shape: stored_data
    files
    dir_path
    dir_name
  }
  OutputDir {
    shape: stored_data
    None
  }
}

"InputDir::new" -> output_rename
user -> output_rename: output_path
user -> output_rename: is_move

output_rename -> are_same_directory
are_same_directory {
  shape: diamond
}
are_same_directory -> "InputDir::new".ModifyDir: modify_dir {
  style.stroke: "#a6e3a1"
}
"InputDir::new".ModifyDir -> "InputDir::new".OutputDir: clone {
  style.stroke: "#a6e3a1"
}
are_same_directory -> else: modify_and_output_path {
  source-arrowhead: 1
  style.stroke: "#f38ba8"
}
else {
  creat_output_dir {
    shape: step
  }
  get_dir_name {
    shape: step
  }
}
"InputDir::new".ModifyDir.files -> else.creat_output_dir: copy_or_move {
  source-arrowhead: 1
  style.stroke: "#f38ba8"
}

OutputDir {
  shape: stored_data
}
else.creat_output_dir -> OutputDir.files {
  style.stroke: "#f38ba8"
}
else.get_dir_name -> OutputDir.dir_name {
  style.stroke: "#f38ba8"
}
else -> OutputDir.dir_path {
  style.stroke: "#f38ba8"
}

# transport data
OutputDir -> "rename.rs".same_len {
  style.stroke: "#f38ba8"
}
"InputDir::new".OutputDir -> "rename.rs".same_len: clone {
  style.stroke: "#a6e3a1"
}
"InputDir::new".ModifyDir -> "rename.rs".batch_rename

# 重命名部分
"rename.rs" {
  same_len {
    shape: diamond
  }
  same_len -> batch_rename
  batch_rename -> rename_file -> update_info
  update_info -> _."InputDir::new".OutputDir {
    style.stroke: "#f9e2af"
  }
  update_info -> _.end {
    style.stroke: "#f38ba8"
  }
  same_len-> _.end {
    style.stroke: "#f38ba8"
  }
}
end {
  shape: parallelogram
}
