name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add toolchain PPA
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
        sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpango1.0-dev libgtk-3-dev libglib2.0-dev libgtk-4-dev libcairo2-dev libadwaita-1-dev

    - name: Set PKG_CONFIG_PATH
      run: |
        echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig" >> $GITHUB_ENV

    - name: Check GTK4 version
      run: |
        pkg-config --modversion gtk4
        pkg-config --libs --cflags gtk4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check formatting
      run: cargo fmt -- --check
      continue-on-error: true

    - name: Lint with clippy
      run: cargo clippy
      continue-on-error: true

    - name: Build with verbose output
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
